export const cropcateImages = [
    {
        id:1,
        image:"https://images.squarespace-cdn.com/content/v1/53f2223ee4b0516cd60b393d/1470077593326-J4SKCI4RTHFA71NI1KFE/image-asset.jpeg"
    },
    {
        id:2,
        image:"https://images.pexels.com/photos/1313267/pexels-photo-1313267.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        id:3,
        image:"https://images.pexels.com/photos/365839/pexels-photo-365839.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        id:4,
        image:"https://images.pexels.com/photos/1459331/pexels-photo-1459331.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        id:5,
        image:"https://images.pexels.com/photos/326005/pexels-photo-326005.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        id:6,
        image:"https://images.pexels.com/photos/47305/bananas-banana-shrub-fruits-yellow-47305.jpeg?auto=compress&cs=tinysrgb&w=600"
    }
]

export const recomendCropsImages = [
    {
        id:1,
        image:"https://images.pexels.com/photos/87626/paprika-vegetables-green-food-87626.jpeg?auto=compress&cs=tinysrgb&w=600",
        title:"name",
        status:"ring",
        price:"amount",
        icon:"lock"
    },
    {
        id:2,
        image:"https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?auto=compress&cs=tinysrgb&w=600",
        title:"name",
        status:"ring",
        price:"amount",
        icon:"lock"
    },
    {
        id:3,
        image:"https://images.pexels.com/photos/9591187/pexels-photo-9591187.jpeg?auto=compress&cs=tinysrgb&w=600",
        title:"name",
        status:"ring",
        price:"amount",
        icon:"lock"
    },
    {
        id:4,
        image:"https://images.pexels.com/photos/248420/pexels-photo-248420.jpeg?auto=compress&cs=tinysrgb&w=600",
        title:"name",
        status:"ring",
        price:"amount",
        icon:"lock"
    },
    {
        id:5,
        image:"https://images.pexels.com/photos/13059602/pexels-photo-13059602.jpeg?auto=compress&cs=tinysrgb&w=600",
        title:"name",
        status:"ring",
        price:"amount",
        icon:"lock"
    },
    {
        id:6,
        image:"https://media.istockphoto.com/id/1388403435/photo/fresh-carrots-isolated-on-white-background.jpg?b=1&s=612x612&w=0&k=20&c=aN2rNiqJ5M58B1JyyrTqnRlundqAo3ObRwftBErRCLs=",
        title:"name",
        status:"ring",
        price:"amount",
        icon:"lock"
    },
    {
        id:7,
        image:"https://images.pexels.com/photos/4110476/pexels-photo-4110476.jpeg?auto=compress&cs=tinysrgb&w=600",
        title:"name",
        status:"ring",
        price:"amount",
        icon:"lock"
    },
    {
        id:8,
        image:"https://images.pexels.com/photos/1630588/pexels-photo-1630588.jpeg?auto=compress&cs=tinysrgb&w=600",
        title:"name",
        status:"ring",
        price:"amount",
        icon:"lock"
    },
]